"""add_created_updated_at_to_projects

Revision ID: 97448a6eb206
Revises: 002
Create Date: 2025-09-24 20:33:02.867027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97448a6eb206'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_instructor_email', table_name='instructor')
    op.drop_index('ix_instructor_id', table_name='instructor')
    op.drop_table('instructor')
    op.drop_index('ix_project_id', table_name='project')
    op.drop_table('project')
    op.add_column('classrooms', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('instructors', sa.Column('name', sa.String(), nullable=True))
    op.add_column('instructors', sa.Column('bitirme_count', sa.Integer(), nullable=True))
    op.add_column('instructors', sa.Column('ara_count', sa.Integer(), nullable=True))
    op.add_column('instructors', sa.Column('total_load', sa.Integer(), nullable=True))
    op.add_column('instructors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('instructors', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('instructors', 'department',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_instructors_email', table_name='instructors')
    op.create_index(op.f('ix_instructors_name'), 'instructors', ['name'], unique=False)
    op.create_index(op.f('ix_instructors_type'), 'instructors', ['type'], unique=False)
    op.create_foreign_key(None, 'instructors', 'users', ['user_id'], ['id'])
    op.drop_column('instructors', 'is_active')
    op.drop_column('instructors', 'full_name')
    op.drop_column('instructors', 'email')
    op.drop_column('instructors', 'hashed_password')
    op.drop_column('instructors', 'research_interests')
    op.drop_column('instructors', 'max_project_count')
    op.alter_column('project_assistants', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_assistants', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('projects', sa.Column('description', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('student_capacity', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'is_active')
    op.drop_column('projects', 'student_capacity')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'description')
    op.alter_column('project_assistants', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_assistants', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('instructors', sa.Column('max_project_count', sa.INTEGER(), nullable=True))
    op.add_column('instructors', sa.Column('research_interests', sa.TEXT(), nullable=True))
    op.add_column('instructors', sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False))
    op.add_column('instructors', sa.Column('email', sa.VARCHAR(length=255), nullable=False))
    op.add_column('instructors', sa.Column('full_name', sa.VARCHAR(length=255), nullable=False))
    op.add_column('instructors', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'instructors', type_='foreignkey')
    op.drop_index(op.f('ix_instructors_type'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_name'), table_name='instructors')
    op.create_index('ix_instructors_email', 'instructors', ['email'], unique=1)
    op.alter_column('instructors', 'department',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('instructors', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('instructors', 'user_id')
    op.drop_column('instructors', 'total_load')
    op.drop_column('instructors', 'ara_count')
    op.drop_column('instructors', 'bitirme_count')
    op.drop_column('instructors', 'name')
    op.drop_column('classrooms', 'location')
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('student_capacity', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('advisor_id', sa.INTEGER(), nullable=False),
    sa.Column('co_advisor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['instructor.id'], ),
    sa.ForeignKeyConstraint(['co_advisor_id'], ['instructor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_id', 'project', ['id'], unique=False)
    op.create_table('instructor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.VARCHAR(length=19), nullable=False),
    sa.Column('department', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('research_interests', sa.TEXT(), nullable=True),
    sa.Column('max_project_count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_instructor_id', 'instructor', ['id'], unique=False)
    op.create_index('ix_instructor_email', 'instructor', ['email'], unique=1)
    # ### end Alembic commands ### 