from app.db.base_class import Base
from app.models.user import User
from app.models.instructor import Instructor
from app.models.project import Project
from app.models.classroom import Classroom
from app.models.timeslot import TimeSlot
from app.models.schedule import Schedule
from app.models.audit_log import AuditLog
from app.models.algorithm import AlgorithmRun
from app.models.department import Department 